name: push-to-main
# This action will trigger whenever main gets updated
# success on this action would imply success when we push a release and files are generated
# triggers on PRs or direct commits to main or dev branches
on:
  push:
    branches:
      - main
      - dev  # Added the dev branch her

jobs:
  run-docker:
    # Specifies that the job runs on an Ubuntu environment
    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v4

    # Sets up Docker environment
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # uses the build in container option to build the vm files
    # this test only checks the default build but others should work
    - name: Run Docker command
      run:  |
          cd $GITHUB_WORKSPACE
          chmod +x *.sh
          docker build -t tlm1-builder .
          docker run --rm --interactive --net host --privileged --volume $(pwd):/recipes -v $(pwd)/images/:/images --workdir /recipes tlm1-builder ./build_tracelabsiso_recipe.sh